### ISSUE TITLE
Credit card/identity autofill feature

### ISSUE THREAD

**Issue by soulforged16** [protonpass/ios-pass#1]
Looking to switch over full time from 1Password to Proton Pass. Would like to request a credit card & identity (name, address, email etc.) autofill option be added to Proton Pass. I use these 2 features constantly on 1Pass.

Examples below:

![1pass-identity](https://github.com/protonpass/ios-pass/assets/105093034/026d03ca-1d3d-4dab-9d47-3df00a920340)
![1pass-card](https://github.com/protonpass/ios-pass/assets/105093034/127c9c72-26dc-466e-8755-e3b5e90076d7)

**Comment by ntnhon** [comment]
Hi,
They are both on our roadmap.
Feel free to help us prioritise by voting here: https://protonmail.uservoice.com/forums/953584-proton-pass
